samochody/urls.py
from django.contrib import admin
from django.urls import path
from samochody_web import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.indexView, name='indexView'),
]

samochody_web/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    NAPEDY = [
        ('przedninaped', 'Przedni napęd'),
        ('tylnaped', 'Tylni naped'),
        ('4x4', "Napęd 4x4"),
    ]

    marka = models.CharField(max_length=30, blank=False, unique=False)
    model = models.CharField(max_length=30, blank=False, unique=False)
    silnik = models.CharField(max_length=10, blank=False, unique=False)
    skrzynia_biegów = models.CharField(max_length=20, blank=False, unique=False)
    drzwi = models.IntegerField(blank=False, unique=False)
    rok = models.PositiveSmallIntegerField(default=2023)
    naped = models.CharField(max_length=20, choices=NAPEDY, blank=False, unique=False)

    def __str__(self):
        return f"{self.marka} {self.model} {self.silnik} {self.skrzynia_biegów} {self.drzwi} {self.rok} {self.naped}"

samochody_web/views.py
from django.shortcuts import render
from .models import Article

# Create your views here.
def indexView(request):
    articles = Article.objects.all()
    return render(request, 'index.html', {'articles': articles})

templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Salon samochodowy</title>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <h1>Salon samochodowy</h1>
    <table>
        <tr>
            <th>Marka</th>
            <th>Model</th>
            <th>Silnik</th>
            <th>Skrzynia biegów</th>
            <th>Drzwi</th>
            <th>Rok</th>
            <th>Napęd</th>
        </tr>
        {% for article in articles %}
            <tr>
                <td>{{ article.marka }}</td>
                <td>{{ article.model }}</td>
                <td>{{ article.silnik }}</td>
                <td>{{ article.skrzynia_biegów }}</td>
                <td>{{ article.drzwi }}</td>
                <td>{{ article.rok }}</td>
                <td>{{ article.get_naped_display }}</td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>